spring.datasource.url=jdbc:postgresql://${SERVER_IP}:${SERVER_PG_PORT}/my_project_db
spring.datasource.username=my_app_user
spring.datasource.password=${SERVER_PG_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



