apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-pack-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      # 如果你的镜像拉取很慢，可以尝试提前手动：k3s ctr images pull ghcr.io/zentrix566/java-pack-test:latest
      containers:
        - name: java-app
          image: ghcr.io/zentrix566/java-pack-test:latest
          imagePullPolicy: IfNotPresent  # 如果本地有镜像就不去外网拉取，提速关键
          ports:
            - containerPort: 8080
          env:
            # Spring Boot 识别环境变量的规则：全大写，下划线代替点
            # 这将直接覆盖代码里的 spring.datasource.url
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://172.17.107.89:25542/my_project_db"

            - name: SPRING_DATASOURCE_USERNAME
              value: "my_app_user"

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-db-secret
                  key: password

          # 增加内存限制，防止 Java 把 2G 内存吃光导致宿主机死机
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: java-app-service
spec:
  type: NodePort
  selector:
    app: java-app
  ports:
    - protocol: TCP
      port: 80           # 集群内访问端口（Nginx 转发用这个）
      targetPort: 8080   # 容器内 Spring Boot 监听端口
      nodePort: 30080    # 外部直接访问端口