apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-pack-test
  labels:
    app: java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      # 1. 核心：必须引用上面创建的 Secret 才能从私有库拉取
      imagePullSecrets:
        - name: aliyun-pull-secret
      containers:
        - name: java-app
          # 2. 核心：使用阿里云 ACR 个人版完整镜像地址
          image: crpi-nfo20s3jyve6dt2s.cn-beijing.personal.cr.aliyuncs.com/zentrix-repo/java-pack-test:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            # 3. 环境变量注入：Spring Boot 标准格式（直接覆盖 properties）
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://172.17.107.89:25542/my_project_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "my_app_user"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-db-secret
                  key: password
          # 资源限制：防止 2G 内存被 Java 撑爆
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "800Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: java-app-service
spec:
  type: NodePort
  selector:
    app: java-app
  ports:
    - protocol: TCP
      port: 80           # 集群内部通信端口 (Nginx 访问这个)
      targetPort: 8080   # 容器内部端口
      nodePort: 30080    # 外部公网访问端口