apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-pack-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java-app
          # 这里的镜像地址会被 GitHub Actions 的 sed 命令动态替换
          image: ghcr.io/zentrix566/java-pack-test:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-app-service
spec:
  type: NodePort
  selector:
    app: java-app
  ports:
    - protocol: TCP
      port: 80         # 集群内访问端口
      targetPort: 8080   # 容器内监听端口
      nodePort: 30080    # 外部访问端口，通过 服务器IP:30080 访问